services:
  - type: web
    name: ecovision-ai
    runtime: python
    pythonVersion: "3.11.9"
    rootDir: api_ai
    buildCommand: pip install -r render_requirements.txt
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TF_USE_LEGACY_KERAS
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.9"
